val ident : 'a -> 'a
val trap : 'a -> 'a
val fcmp : 'a -> 'a
val fun_ : 'a -> 'a
val feql : 'a -> 'a
val fadd : 'a -> 'a
val fix : 'a -> 'a
val fsub : 'a -> 'a
val fixu : 'a -> 'a
val flot : 'a -> 'a
val floti : 'a -> 'a
val flotu : 'a -> 'a
val flotui : 'a -> 'a
val sflot : 'a -> 'a
val sfloti : 'a -> 'a
val sflotu : 'a -> 'a
val sflotui : 'a -> 'a
val fmul : 'a -> 'a
val fcmpe : 'a -> 'a
val fune : 'a -> 'a
val feqle : 'a -> 'a
val fdiv : 'a -> 'a
val fsqrt : 'a -> 'a
val frem : 'a -> 'a
val fint : 'a -> 'a
val zsn : 'a -> 'a
val zsni : 'a -> 'a
val zsz : 'a -> 'a
val zszi : 'a -> 'a
val zsp : 'a -> 'a
val zspi : 'a -> 'a
val zsod : 'a -> 'a
val zsodi : 'a -> 'a
val zsnn : 'a -> 'a
val zsnni : 'a -> 'a
val zsnz : 'a -> 'a
val zsnzi : 'a -> 'a
val zsnp : 'a -> 'a
val zsnpi : 'a -> 'a
val zsev : 'a -> 'a
val zsevi : 'a -> 'a
val ldsf : 'a -> 'a
val ldsfi : 'a -> 'a
val cswap : 'a -> 'a
val cswapi : 'a -> 'a
val ldunc : 'a -> 'a
val ldunci : 'a -> 'a
val ldvts : 'a -> 'a
val ldvtsi : 'a -> 'a
val preld : 'a -> 'a
val preldi : 'a -> 'a
val prego : 'a -> 'a
val pregoi : 'a -> 'a
val stsf : 'a -> 'a
val stsfi : 'a -> 'a
val stht : 'a -> 'a
val sthti : 'a -> 'a
val stco : 'a -> 'a
val stcoi : 'a -> 'a
val stunc : 'a -> 'a
val stunci : 'a -> 'a
val syncd : 'a -> 'a
val syncdi : 'a -> 'a
val prest : 'a -> 'a
val presti : 'a -> 'a
val syncid : 'a -> 'a
val syncidi : 'a -> 'a
val pushgo : 'a -> 'a
val pushgoi : 'a -> 'a
val more : 'a -> 'a
val morei : 'a -> 'a
val mxor : 'a -> 'a
val mxori : 'a -> 'a
val sethmh : 'a -> 'a
val setml : 'a -> 'a
val setl : 'a -> 'a
val inch : 'a -> 'a
val incmh : 'a -> 'a
val incml : 'a -> 'a
val incl : 'a -> 'a
val orh : 'a -> 'a
val ormh : 'a -> 'a
val orml : 'a -> 'a
val orl : 'a -> 'a
val andnh : 'a -> 'a
val andnmh : 'a -> 'a
val andnml : 'a -> 'a
val andnl : 'a -> 'a
val pushj : 'a -> 'a
val pushjb : 'a -> 'a
val put : 'a -> 'a
val puti : 'a -> 'a
val pop : 'a -> 'a
val resume : 'a -> 'a
val save : 'a -> 'a
val unsave : 'a -> 'a
val sync : 'a -> 'a
val swym : 'a -> 'a
val trip : 'a -> 'a
