type op = Machine.machine -> Machine.machine
val mul : op
val muli : op
val mulu : op
val mului : op
val div : op
val divi : op
val divu : op
val divui : op
val add : op
val addi : op
val addu : op
val addui : op
val sub : op
val subi : op
val subu : op
val subui : op
val neg : op
val negi : op
val negu : op
val negui : op
val addu2 : op
val addui2 : op
val addu4 : op
val addui4 : op
val addu8 : op
val addui8 : op
val addu16 : op
val addui16 : op
val ldb : op
val ldbi : op
val ldbu : op
val ldbui : op
val ldw : op
val ldwi : op
val ldwu : op
val ldwui : op
val ldt : op
val ldti : op
val ldtu : op
val ldtui : op
val ldo : op
val ldoi : op
val ldou : op
val ldoui : op
val ldht : op
val ldhti : op
val stbu : op
val stbui : op
val stwu : op
val stwui : op
val sttu : op
val sttui : op
val stou : op
val stoui : op
val stco : op
val stcoi : op
val stht : op
val sthti : op
val stb : op
val stbi : op
val stw : op
val stwi : op
val stt : op
val stti : op
val sto : op
val stoi : op
val and_ : op
val andi : op
val or_ : op
val ori : op
val xor_ : op
val xori : op
val andn : op
val andni : op
val orn : op
val orni : op
val nand : op
val nandi : op
val nor : op
val nori : op
val nxor : op
val nxori : op
val mux : op
val muxi : op
val bdif : op
val bdifi : op
val wdif : op
val wdifi : op
val tdif : op
val tdifi : op
val odif : op
val odifi : op
val sadd : op
val saddi : op
val seth : op
val setmh : op
val setlh : op
val setl : op
val orh : op
val ormh : op
val orml : op
val orl : op
val andnh : op
val andnmh : op
val andnml : op
val andnl : op
val slu : op
val slui : op
val sru : op
val srui : op
val sl : op
val sli : op
val sr : op
val sri : op
val cmp : op
val cmpi : op
val cmpu : op
val cmpui : op
val csn : op
val csni : op
val csz : op
val cszi : op
val csp : op
val cspi : op
val csod : op
val csodi : op
val csnn : op
val csnni : op
val csnz : op
val csnzi : op
val csnp : op
val csnpi : op
val csev : op
val csevi : op
val zsz : op
val zszi : op
val zsp : op
val zspi : op
val zsod : op
val zsodi : op
val zsnn : op
val zsnni : op
val zsnz : op
val zsnzi : op
val zsnp : op
val zsnpi : op
val zsev : op
val zsevi : op
val bn : op
val bnb : op
val bz : op
val bzb : op
val bp : op
val bpb : op
val bod : op
val bodb : op
val bnn : op
val bnnb : op
val bnz : op
val bnzb : op
val bnp : op
val bnpb : op
val bev : op
val bevb : op
val pbn : op
val pbnb : op
val pbz : op
val pbzb : op
val pbp : op
val pbpb : op
val pbod : op
val pbodb : op
val pbnn : op
val pbnnb : op
val pbnz : op
val pbnzb : op
val pbnp : op
val pbnpb : op
val pbev : op
val pbevb : op
val geta : op
val getab : op
val jmp : op
val jmpb : op
val go : op
val goi : op
val get : op
val put : op
val puti : op
